/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#0f131d',
        'surface-dim': '#0f131d',
        'surface-bright': '#353944',
        'surface-container-lowest': '#0a0e18',
        'surface-container-low': '#171b26',
        'surface-container': '#1c1f2a',
        'surface-container-high': '#262a35',
        'surface-container-highest': '#313540',
        'on-surface': '#dfe2f1',
        'on-surface-variant': '#b9cacb',
        'inverse-surface': '#dfe2f1',
        'inverse-on-surface': '#2c303b',
        outline: '#849495',
        'outline-variant': '#3a494b',
        'surface-tint': '#00dce6',
        primary: '#e0fdff',
        'on-primary': '#00373a',
        'primary-container': '#00f2fe',
        'on-primary-container': '#006a70',
        'inverse-primary': '#00696f',
        secondary: '#9bcbff',
        'on-secondary': '#003256',
        'secondary-container': '#3196e6',
        'on-secondary-container': '#002c4b',
        tertiary: '#dfffef',
        'on-tertiary': '#003829',
        'tertiary-container': '#00f8bf',
        'on-tertiary-container': '#006d53',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#6ff6ff',
        'primary-fixed-dim': '#00dce6',
        'on-primary-fixed': '#002022',
        'on-primary-fixed-variant': '#004f53',
        'secondary-fixed': '#d0e4ff',
        'secondary-fixed-dim': '#9bcbff',
        'on-secondary-fixed': '#001d34',
        'on-secondary-fixed-variant': '#004a7a',
        'tertiary-fixed': '#31ffc7',
        'tertiary-fixed-dim': '#00e1ad',
        'on-tertiary-fixed': '#002117',
        'on-tertiary-fixed-variant': '#00513d',
        background: '#0f131d',
        'on-background': '#dfe2f1',
        'surface-variant': '#313540',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
      },
      spacing: {
        unit: '4px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '48px',
        'panel-margin': '12px',
        'editor-gutter': '32px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Outfit', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
}
